int comp(long a, long b)
{
    return a < b;
}

long lt_cnt = 0;    
long ge_cnt = 0;

long absdiff_se(long x, long y)
{
    long result;

    if (x < y) goto TRUE;
    ge_cnt++;
    result = x - y;
    goto DONE;
TRUE:
    lt_cnt++;
    result = y - x;
DONE:
    return result;
}


long test_01(long x, long y, long z)
{
    /* 3.18 */
    long val = x + y + z;

    if (x < -3) {
        if (y < z)
            val = x * y;
        else
            val = y * z;
    } else if (x > 2)
        val = x * z;
    return val;
}

long test_02(long x, long y)
{
    /*
    3.21 
    Assemble code generated by compiler is not same to CSAPP's.
    */
    long val = 8 * x;

    if (y > 0) {
        if (x < y)
            val = y - x;
        else
            val = x & y;
    } else if (y <= -2)
        val = x + y;
    return val;
}

long fun_a(unsigned x)
{
    long val = 0;
    while (x) {
        val ^= x;
        x >>= 1;
    }
    return val & 0x1;
}
